logging:
  file: logs/app_dev.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    net.sinou: TRACE
 
spring:
  datasource:
    schema: net/sinou/tutorials/springboot/dummy/schema-all.sql
    